# Generated by Django 3.0.4 on 2021-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodivision', '0002_auto_20210208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartier',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom quartier'),
        ),
    ]
