# Generated by Django 2.2.7 on 2019-11-30 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2019, 12, 21), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birth',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='gestciv.Registration', verbose_name='Père'),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2019, 12, 21), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2019, 12, 21), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié'), ('V', 'Veuf')], default='M', max_length=15, verbose_name='Stuation matrimoniale'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nationality',
            field=django_countries.fields.CountryField(default='BJ', max_length=2, verbose_name='Pays de naissance'),
        ),
    ]
