# Generated by Django 2.2.8 on 2019-12-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0005_auto_20191203_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_reg', to='gestciv.Profession', verbose_name='Profession'),
        ),
    ]
