# Generated by Django 2.2.8 on 2019-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0006_auto_20191203_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='job',
            field=models.CharField(max_length=30, verbose_name='Profession'),
        ),
    ]
