# Generated by Django 2.2.8 on 2019-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0016_auto_20191209_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='nom',
            field=models.CharField(max_length=200, unique=True, verbose_name='Profession'),
        ),
    ]
