# Generated by Django 2.2.8 on 2019-12-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0020_auto_20191210_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='birthcity',
        ),
        migrations.AddField(
            model_name='registration',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_reside', to='gestciv.Arrondissement', verbose_name='Quartier'),
        ),
    ]
