# Generated by Django 2.2.8 on 2019-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0022_auto_20191212_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Profession'),
        ),
    ]
