# Generated by Django 2.2.8 on 2019-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0023_auto_20191212_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=8, verbose_name='Sexe'),
        ),
    ]
