# Generated by Django 2.2.8 on 2019-12-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0025_auto_20191213_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mairie_reside', to='gestciv.Mairie', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arron_reside', to='gestciv.Arrondissement', verbose_name='Arrondissement'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_reside', to='gestciv.Arrondissement', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='street_type',
            field=models.CharField(blank=True, choices=[('Boulevard', 'Boulevard'), ('Avenue', 'Avenue'), ('Cours', 'Cours'), ('Place', 'Place'), ('Rue', 'Rue'), ('Route', 'Route'), ('Voie', 'Voie'), ('Chemin', 'Chemin'), ('Square', 'Square'), ('Impasse', 'Impasse'), ('Rond-point', 'Rond-point'), ('Quai', 'Quai')], default='Rue', max_length=30, null=True, verbose_name='Type de rue'),
        ),
    ]
