# Generated by Django 2.2.8 on 2019-12-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0027_auto_20191214_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrondissement',
            options={'ordering': ['nom'], 'verbose_name': 'Arrondissement', 'verbose_name_plural': 'Arrondissements'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='groupeethnique',
            options={'ordering': ['nom'], 'verbose_name': 'Groupe ethnique', 'verbose_name_plural': 'Groupe ethnique'},
        ),
        migrations.AlterModelOptions(
            name='mairie',
            options={'ordering': ['nom'], 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
    ]
