# Generated by Django 2.2.8 on 2019-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0028_auto_20191214_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personne à joindre'),
        ),
    ]
