# Generated by Django 2.2.8 on 2019-12-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0029_registration_ice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ice_registration', to='gestciv.Registration', verbose_name='Personne à joindre'),
        ),
    ]
