# Generated by Django 2.2.8 on 2019-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0030_auto_20191214_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='arrived_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée"),
        ),
    ]
