# Generated by Django 2.2.8 on 2019-12-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestciv', '0032_auto_20191215_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('eventlocation', models.CharField(max_length=30, verbose_name='Lieu de décès')),
                ('reglocation', models.CharField(max_length=30, verbose_name="Lieu d'enregistrement")),
                ('cause', models.CharField(max_length=30, verbose_name='cause du décès')),
                ('deathday', models.DateField(verbose_name='Date de décès')),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifier_death', to=settings.AUTH_USER_MODEL, verbose_name='Le certificateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestciv_death_add', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestciv_death_update', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_registration', to='gestciv.Registration', verbose_name='Administré')),
            ],
            options={
                'verbose_name': 'Décès',
                'verbose_name_plural': 'Décès',
            },
        ),
    ]
