# Generated by Django 2.2.8 on 2019-12-26 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestciv', '0033_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro identifiant privé'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 16), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 16), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 16), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.CreateModel(
            name='FetalDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('deathday', models.DateField(verbose_name='Date de décès')),
                ('eventlocation', models.CharField(max_length=30, verbose_name='Lieu de décès')),
                ('regday', models.CharField(max_length=30, verbose_name="Lieu d'enregistrement")),
                ('cause', models.CharField(max_length=30, verbose_name='cause du décès')),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifier_fetaldeath', to=settings.AUTH_USER_MODEL, verbose_name='Le certificateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestciv_fetaldeath_add', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestciv_fetaldeath_update', to=settings.AUTH_USER_MODEL)),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_death_registration', to='gestciv.Registration', verbose_name='NIP de la mère')),
            ],
            options={
                'verbose_name_plural': 'Morts foetales',
                'verbose_name': 'Mort foetale',
            },
        ),
    ]
