# Generated by Django 2.2.8 on 2020-01-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0035_auto_20200104_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdeclaration',
            name='birthcountry',
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='birthcity',
            field=models.CharField(max_length=30, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='midwifegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_de_la_sage_femme', to='auth.Group', verbose_name='Arrondissement de déclaration'),
        ),
    ]
