# Generated by Django 2.2.8 on 2020-01-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0036_auto_20200104_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdeclaration',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_birth_dec', to='gestciv.Quartier', verbose_name='Quartier'),
        ),
    ]
