# Generated by Django 2.2.8 on 2020-01-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0037_birthdeclaration_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdeclaration',
            name='birthcity',
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_birth_dec', to='gestciv.Quartier', verbose_name='Lieu de naissance'),
        ),
    ]
