# Generated by Django 2.2.8 on 2020-01-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0038_auto_20200104_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdeclaration',
            old_name='midwifegroup',
            new_name='district',
        ),
    ]
