# Generated by Django 2.2.8 on 2020-01-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0039_auto_20200104_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_reside', to='gestciv.Quartier', verbose_name='Quartier'),
        ),
    ]
