# Generated by Django 2.2.8 on 2020-01-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0040_auto_20200104_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdeclaration',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_de_la_sage_femme', to='gestciv.Arrondissement', verbose_name='Arrondissement de déclaration'),
        ),
    ]
