# Generated by Django 2.2.8 on 2020-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0044_auto_20200109_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ethnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethnie_reside', to='geodivision.GroupeEthnique', verbose_name='Ethnie'),
        ),
        migrations.DeleteModel(
            name='GroupeEthnique',
        ),
    ]
