# Generated by Django 2.2.8 on 2020-02-03 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0049_auto_20200127_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='birthtype',
            field=models.CharField(blank=True, choices=[('1', 'Simple'), ('2', 'Jumeau'), ('3', 'Triplé'), ('4', 'Quadruplé')], default='Simple', max_length=8, null=True, verbose_name='Type de naissance'),
        ),
        migrations.AddField(
            model_name='birthdeclaration',
            name='birthtype',
            field=models.CharField(blank=True, choices=[('1', 'Simple'), ('2', 'Jumeau'), ('3', 'Triplé'), ('4', 'Quadruplé')], default='Simple', max_length=8, null=True, verbose_name='Type de naissance'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 24), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 24), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 24), null=True, verbose_name="Date d'échéance"),
        ),
    ]
