# Generated by Django 2.2.8 on 2020-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0050_auto_20200203_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birthtype',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Jumeau', 'Jumeau'), ('Triplé', 'Triplé'), ('Quadruplé', 'Quadruplé'), ('Autre', 'Autre')], default='Simple', max_length=8, null=True, verbose_name='Type de naissance'),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='birthtype',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Jumeau', 'Jumeau'), ('Triplé', 'Triplé'), ('Quadruplé', 'Quadruplé'), ('Autre', 'Autre')], default='Simple', max_length=8, null=True, verbose_name='Type de naissance'),
        ),
    ]
