# Generated by Django 3.0.4 on 2021-02-09 11:28

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestciv', '0054_auto_20200226_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='birth',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 2), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 2), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='bcduedate',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 2), null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nationality',
            field=django_countries.fields.CountryField(default='BJ', max_length=255, verbose_name='Pays de naissance'),
        ),
    ]
